### ISSUE TITLE
Small changes required for an upcoming Atom release

### ISSUE THREAD

**Issue by maxbrunsfeld** [kaitoy/impress#1]
Hi! Atom will soon be upgrading to a new version of Electron, which will cause some APIs to change.

You'll need to:
- change [this usage](https://github.com/kaitoy/impress/blob/dc0affe5bc9e40352164a06bc02851bdc527d08a/lib/impress.coffee#L72) of `BrowserWindow.prototype.loadUrl` to `@previewWindow.webContents.loadURL`.
- change `require("remote")` to `require("electron").remote`
- change `remote.require("browser-window")` to `remote.BrowserWindow`

There may be other similar small changes required. See [this post](http://electron.atom.io/blog/2015/11/17/electron-api-changes) on the electron blog for more information. And let me know if you need any additional help. Thanks!

**Comment by kaitoy** [comment]
Thank you for the information.
I made the changes and released a new version.
